var mitkNavigationToolStorageSerializerAndDeserializerIntegrationTest_8cpp =
[
    [ "mitkNavigationToolStorageSerializerAndDeserializerIntegrationTestSuite", "classmitkNavigationToolStorageSerializerAndDeserializerIntegrationTestSuite.html", "classmitkNavigationToolStorageSerializerAndDeserializerIntegrationTestSuite" ]
];