set(CUSTOM_DEPENDENCIES
  OpenCV
)

set(CUSTOM_CMAKE_ARGS
  -DModule_ITKVideoBridgeOpenCV:BOOL=ON
  -DOpenCV_DIR:PATH=${OpenCV_DIR}
  "-DCMAKE_CONFIGURATION_TYPES:STRING=${CMAKE_CONFIGURATION_TYPES}"
)
