name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doxygen_version: 1.12.0
          config_folder: Documentation/local-doxygen.conf